### PR TITLE
Use poetry to manage Python packaging

### PR DESCRIPTION
**Pull request by bostonrwalker**
Use poetry to manage building Python extension instead of shell script

```
cd pkg/pypi
poetry build
```

### CODE REVIEW

**Comment by bostonrwalker** [comment]
This PR is not dependent on #161, but #161 really should be merged first to avoid issues with names of generated files.

**Comment by joseph-henry** [comment]
Thanks. I've tested all of your PRs and everything seems to work and I can build the wheel with poetry. This is excellent work! Before I merge everything into `dev` I still need to figure out how to tie in poetry with the current use of `cbuildwheel` in [.github/workflows/wheels.yml](https://github.com/zerotier/libzt/blob/master/.github/workflows/wheels.yml). Let me know if you have any thoughts on this or if there is another tool you think would be better.

**Comment by bostonrwalker** [comment]
> 
Looks like there are actions available for GitHub workflows that install poetry (e.g. https://github.com/marketplace/actions/setup-poetry). Then you can run `poetry env use 3.x` where `x` is the version of Python you want to build for and `poetry build` to build the wheel.

I played around with this and I was able to build wheels this way for multiple versions of Python. A caveat is there seems to be a bug in the latest version of poetry that causes the name of the output wheel to always reflect the same version of Python (i.e. the wheel I got was always called `libzt-1.8.4-cp310...`, even when I built for 3.9, 3.8, etc.). The wheel is still built against the correct version of Python so this is fixed by just renaming the file.

**Comment by bostonrwalker** [comment]
Reference: https://github.com/python-poetry/poetry/issues/3509. I wouldn't hold my breath for a resolution as poetry extension module support is still very alpha-stage for some reason even after 3 years.

**Comment by bostonrwalker** [comment]
RE: **cibuildwheel**, it looks like Poetry _might_ already be supported: https://github.com/pypa/cibuildwheel/issues/916. Also, it would be a good idea to add Python 3.10 support now.

**Comment by bostonrwalker** [comment]
I took a stab at retooling wheels.yml. It's not tested though.

**Comment by bostonrwalker** [comment]
**Note**: I just removed support for Python 3.5 since it is not supported by Poetry and it is currently being phased out. I don't think we can migrate to Poetry without making this change.

**Comment by bostonrwalker** [comment]
setup.py needs to be removed as well for this one to work.

**Pull request merged**
