### PR TITLE
Nodejs bindings

### PR DESCRIPTION
**Pull request by janvanbouwel**
see #234

### CODE REVIEW

**Comment by janvanbouwel** [comment]
This accidentally includes the changes from #210 which have not been merged. I can take them out if necessary (though would obviously prefer them to be merged).

**Comment by joseph-henry** [comment]
It's ok, your java changes seem reasonable so I'll just try to merge the whole thing in. I'm a novice when it comes to node so I'll poke at this and probably have some questions for you soon.

Thanks again for all of this.

**Comment by joseph-henry** [comment]
So, things seem to build:

```
cd src/bindings/nodejs
npm install
npm run prebuild
npm run build
```

and I get:

```
├── binding.Makefile
├── config.gypi
├── Makefile
├── node_gyp_bins
│   └── python3 -> /home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11
├── Release
│   ├── obj.target
│   │   ├── zts
│   │   └── zts.node
│   └── zts.node
└── zts.target.mk
```

Upon inspecting `zts.node` I can see it has the necessary libzt symbols and is valid ELF, but I have a couple questions:

 - Is what you put in `./attic` just for historical reasons or is that still relevant somehow? I don't have any problem with it being there but I am curious.

**Comment by janvanbouwel** [comment]
@joseph-henry 
Last commit (241f207) is a nice one, as I switched from `node-gyp` to `cmake-js`, which can reuse the already existing CMakeLists.txt, and it is no longer required to first manually build using the `build.sh` script. (As a consequence, the existing OS detection means Windows and MacOS might work now too, but I can't test this.)  

I'm very new to build systems and cmake so it builds but definitely take a look.

On a different note, I discoverd lwip's [callback API](https://github.com/zerotier/lwip/blob/master/src/include/lwip/tcp.h) yesterday, which looks far superior than the `AsyncWorker` I've been using to integrate with node.  I'm gonna look at using these instead of the bsd-style functions (which will be far more convenient using cmake-js).

If you have any tips, notes or questions let me know!

**Comment by janvanbouwel** [comment]
Moved development to https://github.com/janvanbouwel/libzt-node.

**Pull request closed without merging**
